version: '3.8'

x-service: &service
  tty: true
  stdin_open: true
  restart: 'unless-stopped'

x-node: &node
  << : *service
  user: "${UID:-1000}:${GID:-1000}"
  build:
    context: .
    dockerfile: Dockerfile.Node
    args:
      UID: "${UID:-1000}"
      GID: "${GID:-1000}"

services:
  web-app:
    << : *node
    container_name: web-app
    working_dir: /home/node/web-app
    volumes:
      - web_storage:/home/node/web-app
    command: bash -c "CI=1 pnpm i && pnpm dev"
    ports:
      - "4321:4321"
    networks:
      - buddy-network
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 6G

  # Reverse proxy Nginx
  nginx-proxy:
     image: nginx:alpine
     container_name: proxy
     network_mode: host
     volumes:
       - ./nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
     restart: unless-stopped

  buddy-api:
    build:
      context: .
      dockerfile: BetBuddy.Backend/Dockerfile
    container_name: buddy-api
    ports:
      - "5200:5200"
    networks:
      - buddy-network
    depends_on:
      - buddy-postgres
      - ollama-server
      - qdrant

  buddy-postgres:
    image: pgvector/pgvector:pg16
    container_name: buddy-postgres
    user: "root"
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=buddy
      - POSTGRES_PASSWORD=MNhl^2AT&E#EZ5G2
    ports:
      - '11005:5432'
    healthcheck:
      test: ["CMD", "pg_isready", "-p", "5448"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - buddy-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ollama-server:
    image: docker.io/ollama/ollama:0.12.3
    ports:
      - 11004:11434
    volumes:
      -  ollama_data:/code
      -  ollama_data:/root/.ollama
    container_name: ollama-server
    pull_policy: always
    tty: true
    restart: always
    environment:
      - OLLAMA_OPENAI_API=true
      - OLLAMA_ENABLE_TOOLS=true
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    networks:
      - buddy-network

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    networks:
      - buddy-network

networks:
  buddy-network:
    driver: bridge

volumes:
  ollama_data:
    driver: local
  postgres_data:
    driver: local
  qdrant_storage:
    driver: local
  web_storage:
    driver: local